//
// Amount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Amount: Codable {

    public var value: Double?
    public var unit: String?

    public init(value: Double?, unit: String?) {
        self.value = value
        self.unit = unit
    }

}
