//
// Beer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Beer: Codable {

    public var id: Int64?
    public var name: String?
    public var description: String?
    public var firstBrewed: String?
    public var imageUrl: String?
    public var ingredients: Ingredients?

    public init(id: Int64?, name: String?, description: String?, firstBrewed: String?, imageUrl: String?, ingredients: Ingredients?) {
        self.id = id
        self.name = name
        self.description = description
        self.firstBrewed = firstBrewed
        self.imageUrl = imageUrl
        self.ingredients = ingredients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case description
        case firstBrewed = "first_brewed"
        case imageUrl = "image_url"
        case ingredients
    }

}
