//
// Ingredients.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Ingredients: Codable {

    public var malt: [MaltIngredient]?
    public var hops: [HopsIngredient]?
    public var yeast: String?

    public init(malt: [MaltIngredient]?, hops: [HopsIngredient]?, yeast: String?) {
        self.malt = malt
        self.hops = hops
        self.yeast = yeast
    }

}
