//
// Journal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Journal: Codable {

    public var items: [JournalItem]?

    public init(items: [JournalItem]?) {
        self.items = items
    }

}
