//
// MaltIngredient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MaltIngredient: Codable {

    public var name: String?
    public var amount: Amount?

    public init(name: String?, amount: Amount?) {
        self.name = name
        self.amount = amount
    }

}
