swagger: "2.0"
info:
  description: "BeersApi"
  version: "1.0.0"
  title: "BeersApi"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.punkapi.com"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /beers:
    get:
      tags:
      - "beers"
      summary: "get beers"
      operationId: "getBeers"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "page"
        in: "query"
        description: "Page"
        required: false
        type: "integer"
      - name: "per_page"
        in: "query"
        description: "per page"
        required: false
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Beer"
        400:
          description: "Invalid status value"
  /beers/{id}:
    get:
      tags:
      - "beers"
      summary: "Find beer by ID"
      description: "Returns a single beer"
      operationId: "getBeerById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of beer to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Beer"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Beer not found"
   
definitions:
  Ingredients:
    type: "object"
    properties:
      malt:
        type: "array"
        items:
          $ref: "#/definitions/MaltIngredient"
      hops:
        type: "array"
        items:
          $ref: "#/definitions/HopsIngredient"
      yeast:
        type: "string"
  MaltIngredient:
    type: "object"
    properties:
      name:
        type: "string"
      amount: 
       $ref: "#/definitions/Amount"
  HopsIngredient:
    type: "object"
    properties:
      name:
        type: "string"
      add:
        type: "string"
      attribute:
        type: "string"
      amount: 
       $ref: "#/definitions/Amount"
  Amount:
    type: "object"
    properties:
      value: 
        type: "number"
      unit:
        type: "string"
  Beer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      first_brewed:
        type: "string"
      image_url:
        type: "string"
      ingredients:
        $ref: "#/definitions/Ingredients"
    xml:
      name: "Beer"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"